service: myfirstlambdav1
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
        - sns:*
      Resource: '*'
      
functions:
  sayhelloapi:
    handler: src/handlers/hello.handler
    events:
      - httpApi:
          path: /hello
          method: get
  sendsqsapi:
    handler: src/handlers/sendsqs.handler
    events:
      - httpApi:
          path: /sqs
          method: post
    environment: ${file(env.json)}
  sqstosnsapi:
    handler: src/handlers/sqstosns.handler
    events: 
      - sqs:
          arn: arn:aws:sqs:eu-west-2:533322355632:myfirstsqsqueue
          batchSize: 1

