service: myfirstlambdav1
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2

functions:
  sayhelloapi:
    handler: src/handlers/hello.handler
    events:
      - httpApi:
          path: /
          method: get
